### ISSUE TITLE
Sign in screen in mobile is covered by keyboards

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-3#844]
PatternFly sign in screens are often covered by keyboards when trying to sign in from a mobile browser.

This affects both Chrome and Firefox (although Firefox _sometimes_ seems to try to accommodate a little bit by scrolling an element or two into the screen­ — but not always).

Here are a few screenshots to illustrate the problem:

## Example log in screen (in Chrome)

| initial | focus |
|---|---|
| ![screenshot_20171116-151759](https://user-images.githubusercontent.com/10246/32895979-127a37c8-cae2-11e7-8926-5340eec4d4cf.png) | ![screenshot_20171116-151803](https://user-images.githubusercontent.com/10246/32895983-152b84fe-cae2-11e7-9ed3-7065cc79cd49.png) |

## In the wild (in Firefox)

| initial | focus |
|---|---|
| ![screenshot_20171116-151656](https://user-images.githubusercontent.com/10246/32896082-5ebbc9f8-cae2-11e7-89e8-11d0fb9383a2.png) | ![screenshot_20171116-151701](https://user-images.githubusercontent.com/10246/32896065-4edd7f2c-cae2-11e7-942e-450b5078f9cb.png) |

---

## Solution (recently implemented in Cockpit)

I noticed this issue when we were implementing new navigation for Cockpit and was a bit frustrated signing in and having to scroll around as well as trying to enter text in the browser.

My solution was to use flexbox to reorder the elements in on smaller portrait screens (desktop & tablets are the same) so the sign in form is right at the top.

| initial | focus |
|---|---|
| ![screenshot_20171114-122106](https://user-images.githubusercontent.com/10246/32777606-17a121aa-c937-11e7-84fb-ac2511707eb0.png) | ![screenshot_20171114-123513](https://user-images.githubusercontent.com/10246/32777933-6bb508c8-c938-11e7-8a77-ecd4e00e55ef.png) |

For Cockpit, the issue was @ https://github.com/cockpit-project/cockpit/issues/8035 and the changes we merged in are at https://github.com/cockpit-project/cockpit/pull/8092/files

Notes: 

1. The CSS for our login page is copy/pasted from parts of PatternFly and is minimized and inlined. Still, the CSS I included should be able to be adapted pretty easily for inclusion.
2. These changes also include some keyboard directives in the HTML for disabling auto-capitalization for usernames as well as in-line auto-correction.

**Comment by andresgalante** [comment]
Hi @garrett Thanks for reporting it. We are working with the keycloak team on a more flexible and improved login screen. I'll make sure to test the keyboard on those ones.

I think we can introduce the change you are suggesting for the current login page as long as it doesn't generate breaking changes.

**Comment by matthewcarleton** [comment]
hey @Garrett we now have the new login pages that should resolve this. Can you confirm? [New login page](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-basic.html)

**Comment by LHinson** [comment]
Thanks @matthewcarleton Since the new login resolves this, I'm going to close this issue. Thx!

**Comment by andreasn** [comment]
It seems it was not fixed in the new design.

**Comment by andreasn** [comment]
So we'll need to reopen this issue I think

**Comment by garrett** [comment]
Confirmed still not work as expected with the new login screen on mobile. Brosers tested: Android System WebView (Blink, the Chrome engine) and Firefox, both on Android.

The keyboard still fills half the screen, which means it covers password and the login button. It's especially problematic when there is text under the logo.

Two solutions: Invert the layout with the logo under functional part of the login screen (as we did in Cockpit) or use JavaScript to scroll the window to the top when the form is focused.

As the username should probably be focused by default, JavaScript-based scrolling would always hide the logo on mobile. Scrolling via JavaScript is still a little inconsistent between browsers too. In addition, with Cockpit, we have more options that could expand as well, making our own sign in form taller. These are the reasons why we decided to simply use CSS to move the logo underneath and prioritize the form.
